language: c

install:
 - sudo add-apt-repository -y ppa:gstreamer-developers/ppa
 - sudo apt-get update
 - sudo apt-get install
        expect
        gir1.2-gstreamer-1.0
        gir1.2-gudev-1.0
        gstreamer1.0-libav
        gstreamer1.0-plugins-bad
        gstreamer1.0-plugins-base
        gstreamer1.0-plugins-good
        gstreamer1.0-tools
        gstreamer1.0-x
        libgstreamer1.0-dev
        libgstreamer-plugins-base1.0-dev
        libopencv-dev
        liborc-0.4-dev
        lighttpd
        moreutils
        pep8
        pylint
        python-docutils
        python-flask
        python-gobject
        python-jinja2
        python-matplotlib
        python-nose
        python-numpy
        python-opencv
        python-scipy
        tesseract-ocr
        v4l-utils
 - git clone http://git.chromium.org/webm/webminspector.git ~/webminspector
 - GST_DEBUG=3 make prefix=$HOME enable_stbt_camera=yes install

script:
 - gst-inspect-1.0
 - ldd /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstrsvg.so
 - PATH=~/bin:~/webminspector:$PATH make check
